name: dependabot

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  get_current_info:
    runs-on: ubuntu-latest
    outputs:
      pkg_source_version: ${{ steps.info.outputs.pkg_source_version }}
      pkg_mirror_hash: ${{ steps.info.outputs.pkg_mirror_hash }}
      pkg_build_version: ${{ steps.info.outputs.pkg_build_version }}
    steps:
      - name: Checkout OpenWrt-nikki
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: dependabot  # 直接检出dependabot分支
          path: OpenWrt-nikki

      - name: Extract Current Info
        id: info
        run: |
          makefile="OpenWrt-nikki/nikki/Makefile"
          echo "pkg_source_version=$(grep 'PKG_SOURCE_VERSION:=' $makefile | cut -d'=' -f2)" >> $GITHUB_OUTPUT
          echo "pkg_mirror_hash=$(grep 'PKG_MIRROR_HASH:=' $makefile | cut -d'=' -f2)" >> $GITHUB_OUTPUT
          echo "pkg_build_version=$(grep 'PKG_BUILD_VERSION:=' $makefile | cut -d'=' -f2)" >> $GITHUB_OUTPUT

  get_latest_release:
    runs-on: ubuntu-latest
    outputs:
      commit_sha: ${{ steps.release.outputs.commit_sha }}
      checksum: ${{ steps.release.outputs.checksum }}
    steps:
      - name: Get Release Info
        id: release
        run: |
          # 这里保持原有获取最新版本信息的逻辑
          ...

  update:
    needs: [get_current_info, get_latest_release]
    if: ${{ needs.get_current_info.outputs.pkg_source_version != needs.get_latest_release.outputs.commit_sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout dependabot Branch
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: dependabot  # 强制检出目标分支
          path: OpenWrt-nikki
          persist-credentials: true
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"

      - name: Update Makefile
        run: |
          makefile="OpenWrt-nikki/nikki/Makefile"
          # 使用无备份模式修改文件
          sed -i'' \
            -e "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.get_latest_release.outputs.commit_sha }}/" \
            -e "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.get_latest_release.outputs.checksum }}/" \
            $makefile

      - name: Push Changes
        run: |
          cd OpenWrt-nikki
          git add .
          git commit -m "Update mihomo to ${{ needs.get_latest_release.outputs.commit_sha }}"
          git push origin dependabot --force  # 强制推送更新

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          base: main  # 目标分支
          branch: dependabot  # 源分支
          delete-branch: false  # 保留分支
          commit-message: "build: update mihomo"
          title: "build: update mihomo dependency"
          body: "Auto update to latest commit: ${{ needs.get_latest_release.outputs.commit_sha }}"
