name: dependabot

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_info:
    runs-on: ubuntu-latest
    outputs:
      pkg_source_version: ${{ steps.info.outputs.pkg_source_version }}
      pkg_mirror_hash: ${{ steps.info.outputs.pkg_mirror_hash }}
      pkg_build_version: ${{ steps.info.outputs.pkg_build_version }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: main
          path: OpenWrt-nikki
      - id: info
        name: info
        run: |
          echo "pkg_source_version=$(grep "PKG_SOURCE_VERSION:=" OpenWrt-nikki/nikki/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_mirror_hash=$(grep "PKG_MIRROR_HASH:=" OpenWrt-nikki/nikki/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_build_version=$(grep "PKG_BUILD_VERSION:=" OpenWrt-nikki/nikki/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
  get_latest_info:
    runs-on: ubuntu-latest
    outputs:
      commit_date: ${{ steps.info.outputs.commit_date }}
      commit_sha: ${{ steps.info.outputs.commit_sha }}
      short_commit_sha: ${{ steps.info.outputs.short_commit_sha }}
      checksum: ${{ steps.info.outputs.checksum }}
      tag_name: ${{ steps.info.outputs.tag_name }}
    steps:
      - id: fetch_latest_tag
        name: 获取最新标签
        run: |
          # 获取最新标签名
          LATEST_TAG=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/tags | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "获取到的最新标签: $LATEST_TAG"
          
          # 获取标签引用详情
          TAG_INFO=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/git/ref/tags/$LATEST_TAG)
          COMMIT_SHA=$(echo $TAG_INFO | jq -r '.object.sha')
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          echo "标签对应的提交 SHA: $COMMIT_SHA"
          
          # 获取提交详情
          COMMIT_INFO=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/commits/$COMMIT_SHA)
          COMMIT_DATE=$(echo $COMMIT_INFO | jq -r '.commit.committer.date' | cut -d'T' -f1)
          echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
          echo "提交日期: $COMMIT_DATE"
      
      - id: checkout
        name: 检出代码
        uses: actions/checkout@v4
        with:
          repository: 'MetaCubeX/mihomo'
          ref: ${{ env.COMMIT_SHA }}
          path: 'mihomo'
      
      - id: info
        name: 收集信息
        run: |
          echo "commit_date=${{ env.COMMIT_DATE }}" >> $GITHUB_OUTPUT
          echo "commit_sha=${{ env.COMMIT_SHA }}" >> $GITHUB_OUTPUT
          echo "short_commit_sha=$(echo ${{ env.COMMIT_SHA }} | cut -c1-7)" >> $GITHUB_OUTPUT
          echo "tag_name=${{ env.LATEST_TAG }}" >> $GITHUB_OUTPUT
          
          # 创建压缩包并计算校验和
          git -C mihomo config tar.xz.command "xz -c"
          git -C mihomo archive --output=mihomo.tar.xz HEAD
          CHECKSUM=$(sha256sum mihomo.tar.xz | cut -d ' ' -f 1)
          echo "checksum=$CHECKSUM" >> $GITHUB_OUTPUT
          echo "校验和: $CHECKSUM"
  update:
    needs:
      - get_current_info
      - get_latest_info
    if: ${{ needs.get_current_info.outputs.pkg_source_version != needs.get_latest_info.outputs.commit_sha }}
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: main
          path: OpenWrt-nikki
          fetch-depth: 0
          token: ${{ github.token }}
          
      - id: git_config
        name: 配置 Git
        run: |
          cd OpenWrt-nikki
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --all
          git branch -a
          
      - id: update
        name: update
        run: |
          sed -i "s/PKG_RELEASE:=.*/PKG_RELEASE:=1/" OpenWrt-nikki/nikki/Makefile
          sed -i "s/PKG_SOURCE_DATE:=.*/PKG_SOURCE_DATE:=${{ needs.get_latest_info.outputs.commit_date }}/" OpenWrt-nikki/nikki/Makefile
          sed -i "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.get_latest_info.outputs.commit_sha }}/" OpenWrt-nikki/nikki/Makefile
          sed -i "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.get_latest_info.outputs.checksum }}/" OpenWrt-nikki/nikki/Makefile
          sed -i "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=${{ needs.get_latest_info.outputs.tag_name }}/" OpenWrt-nikki/nikki/Makefile
          
      - id: create_pr
        name: 创建 PR
        run: |
          cd OpenWrt-nikki
          git checkout -b dependabot
          git add nikki/Makefile
          git commit -m "build: update mihomo to ${{ needs.get_latest_info.outputs.tag_name }}"
          git push --force origin dependabot
          
          # 使用 GitHub CLI 创建 PR
          gh pr create --title "build: update mihomo to ${{ needs.get_latest_info.outputs.tag_name }}" \
                       --body "将 mihomo 更新到最新标签: ${{ needs.get_latest_info.outputs.tag_name }}
          
          提交: ${{ needs.get_latest_info.outputs.commit_sha }}
          日期: ${{ needs.get_latest_info.outputs.commit_date }}
          
          [更新日志](https://github.com/metacubex/mihomo/compare/${{ needs.get_current_info.outputs.pkg_source_version }}...${{  needs.get_latest_info.outputs.commit_sha }})" \
                       --base main
        env:
          GITHUB_TOKEN: ${{ github.token }}
