name: dependabot
on:
  schedule:
    - cron: "0 0 * * *"  # 每天UTC 0点自动检查
  workflow_dispatch:     # 允许手动触发

jobs:
  get_current_info:
    runs-on: ubuntu-latest
    outputs:
      pkg_source_version: ${{ steps.info.outputs.pkg_source_version }}
      pkg_mirror_hash: ${{ steps.info.outputs.pkg_mirror_hash }}
      pkg_build_version: ${{ steps.info.outputs.pkg_build_version }}
    steps:
      - name: Checkout OpenWrt-nikki
        id: checkout
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: main
          path: OpenWrt-nikki

      - name: Extract Current Package Info
        id: info
        run: |
          makefile="OpenWrt-nikki/nikki/Makefile"
          echo "pkg_source_version=$(grep "PKG_SOURCE_VERSION:=" $makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_mirror_hash=$(grep "PKG_MIRROR_HASH:=" $makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_build_version=$(grep "PKG_BUILD_VERSION:=" $makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT

  get_latest_release:
    runs-on: ubuntu-latest
    outputs:
      tag_name: ${{ steps.release_info.outputs.tag_name }}
      commit_sha: ${{ steps.release_info.outputs.commit_sha }}
      checksum: ${{ steps.release_info.outputs.checksum }}
      release_date: ${{ steps.release_info.outputs.release_date }}
    steps:
      - name: Get Latest Release Metadata
        id: release_info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 提高API速率限制
        run: |
          # 安装JSON解析工具
          sudo apt-get -qq install jq

          # 获取最新release信息
          release_json=$(curl -sH "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/MetaCubeX/mihomo/releases/latest)

          # 提取基础信息
          tag_name=$(jq -r '.tag_name' <<< "$release_json")
          release_date=$(jq -r '.published_at' <<< "$release_json" | cut -d'T' -f1)
          
          # 获取对应commit SHA（假设release基于tag创建）
          tag_info=$(curl -sH "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/MetaCubeX/mihomo/git/ref/tags/$tag_name")
          commit_sha=$(jq -r '.object.sha' <<< "$tag_info")

          # 从官方SHA256SUMS获取校验和
          sha_file_url="https://github.com/MetaCubeX/mihomo/releases/download/$tag_name/SHA256SUMS"
          sha_content=$(curl -sL "$sha_file_url")
          checksum=$(grep "mihomo-linux-arm64-${tag_name#v}.gz" <<< "$sha_content" | awk '{print $1}')

          # 输出变量
          echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
          echo "commit_sha=$commit_sha" >> $GITHUB_OUTPUT
          echo "checksum=$checksum" >> $GITHUB_OUTPUT
          echo "release_date=$release_date" >> $GITHUB_OUTPUT

  update:
    needs: [get_current_info, get_latest_release]
    if: ${{ needs.get_current_info.outputs.pkg_source_version != needs.get_latest_release.outputs.commit_sha }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout OpenWrt-nikki
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: main
          path: OpenWrt-nikki

      - name: Update Makefile
        run: |
          makefile_path="OpenWrt-nikki/nikki/Makefile"
          # 保留原始文件权限
          cp "$makefile_path" "${makefile_path}.bak"
          chmod --reference="${makefile_path}.bak" "$makefile_path"

          # 更新所有字段
          sed -i.bak \
            -e "s/PKG_SOURCE_VERSION:=.*/PKG_SOURCE_VERSION:=${{ needs.get_latest_release.outputs.commit_sha }}/" \
            -e "s/PKG_MIRROR_HASH:=.*/PKG_MIRROR_HASH:=${{ needs.get_latest_release.outputs.checksum }}/" \
            -e "s/PKG_BUILD_VERSION:=.*/PKG_BUILD_VERSION:=${tag_name#v}/" \
            -e "s/PKG_SOURCE_DATE:=.*/PKG_SOURCE_DATE:=${{ needs.get_latest_release.outputs.release_date }}/" \
            "$makefile_path"

          # 验证文件差异
          diff "${makefile_path}.bak" "$makefile_path" || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          path: OpenWrt-nikki
          branch: "dependabot"
          commit-message: "build(mihomo): update to ${{ needs.get_latest_release.outputs.tag_name }}"
          title: "build: update mihomo to ${{ needs.get_latest_release.outputs.tag_name }}"
          body: |
            ## 更新详情
            - **版本**: [${{ needs.get_latest_release.outputs.tag_name }}](https://github.com/MetaCubeX/mihomo/releases/tag/${{ needs.get_latest_release.outputs.tag_name }})
            - **Commit**: [${{ needs.get_latest_release.outputs.commit_sha }}](https://github.com/MetaCubeX/mihomo/commit/${{ needs.get_latest_release.outputs.commit_sha }})
            - **变更日志**: [比较差异](https://github.com/MetaCubeX/mihomo/compare/${{ needs.get_current_info.outputs.pkg_source_version }}...${{ needs.get_latest_release.outputs.commit_sha }})
            - **校验验证**: 使用官方SHA256SUMS文件中的校验值
