name: dependabot

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  get_current_info:
    runs-on: ubuntu-latest
    outputs:
      pkg_version: ${{ steps.info.outputs.pkg_version }}
      pkg_hash: ${{ steps.info.outputs.pkg_hash }}
      pkg_release: ${{ steps.info.outputs.pkg_release }}
    steps:
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: main
          path: OpenWrt-nikki
      - id: info
        name: info
        run: |
          echo "pkg_version=$(grep "PKG_VERSION:=" OpenWrt-nikki/nikki/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_hash=$(grep "PKG_HASH:=" OpenWrt-nikki/nikki/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
          echo "pkg_release=$(grep "PKG_RELEASE:=" OpenWrt-nikki/nikki/Makefile | cut -d '=' -f 2)" >> $GITHUB_OUTPUT
  get_latest_info:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
      hash: ${{ steps.info.outputs.hash }}
      tag_name: ${{ steps.info.outputs.tag_name }}
      release_date: ${{ steps.info.outputs.release_date }}
    steps:
      - id: fetch_latest_tag
        name: 获取最新标签
        run: |
          # 获取最新标签名（去除版本号前缀的 v）
          LATEST_TAG=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/tags | jq -r '.[0].name')
          echo "LATEST_TAG=$LATEST_TAG" >> $GITHUB_ENV
          echo "获取到的最新标签: $LATEST_TAG"
          
          # 提取版本号（去掉前缀 'v'）
          VERSION=$(echo $LATEST_TAG | sed 's/^v//')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "版本号: $VERSION"
          
          # 获取发布日期
          RELEASE_INFO=$(curl -s https://api.github.com/repos/MetaCubeX/mihomo/releases/tags/$LATEST_TAG)
          RELEASE_DATE=$(echo $RELEASE_INFO | jq -r '.published_at' | cut -d'T' -f1)
          echo "RELEASE_DATE=$RELEASE_DATE" >> $GITHUB_ENV
          echo "发布日期: $RELEASE_DATE"
      
      - id: compute_hash
        name: 计算哈希值
        run: |
          # 构建源代码包下载 URL
          DOWNLOAD_URL="https://codeload.github.com/metacubex/mihomo/tar.gz/v${VERSION}?"
          echo "源代码包下载 URL: $DOWNLOAD_URL"
          
          # 下载源代码包
          curl -L -o "mihomo-${VERSION}.tar.gz" "$DOWNLOAD_URL"
          
          # 计算哈希值
          PKG_HASH=$(sha256sum "mihomo-${VERSION}.tar.gz" | cut -d ' ' -f 1)
          echo "源代码包哈希值 (PKG_HASH): $PKG_HASH"
          echo "PKG_HASH=$PKG_HASH" >> $GITHUB_ENV
          
          # 尝试下载预编译二进制文件（仅作为参考）
          echo "========================================="
          echo "尝试下载预编译二进制文件（仅供参考）..."
          
          # 定义要检查的架构
          ARCHS=("arm64" "amd64" "386")
          
          for ARCH in "${ARCHS[@]}"; do
            echo "检查架构: $ARCH"
            # 尝试格式 1: 使用标签名称
            DOWNLOAD_URL="https://github.com/MetaCubeX/mihomo/releases/download/${LATEST_TAG}/mihomo-linux-${ARCH}-${LATEST_TAG}.gz"
            echo "尝试 URL: $DOWNLOAD_URL"
            if curl -s -I "$DOWNLOAD_URL" | grep -q "HTTP/2 200"; then
              echo "找到文件，下载中..."
              curl -L -o "mihomo-${ARCH}.gz" "$DOWNLOAD_URL"
              BIN_CHECKSUM=$(sha256sum "mihomo-${ARCH}.gz" | cut -d ' ' -f 1)
              echo "${ARCH} 二进制文件校验和: $BIN_CHECKSUM"
            else
              echo "未找到 ${ARCH} 的预编译文件"
            fi
          done
          
          echo "========================================="
      
      - id: info
        name: 输出信息
        run: |
          echo "version=${{ env.VERSION }}" >> $GITHUB_OUTPUT
          echo "hash=${{ env.PKG_HASH }}" >> $GITHUB_OUTPUT
          echo "tag_name=${{ env.LATEST_TAG }}" >> $GITHUB_OUTPUT
          echo "release_date=${{ env.RELEASE_DATE }}" >> $GITHUB_OUTPUT
  update:
    needs:
      - get_current_info
      - get_latest_info
    if: ${{ needs.get_current_info.outputs.pkg_version != needs.get_latest_info.outputs.version }}
    runs-on: ubuntu-latest
    steps:
      - id: check_versions
        name: 检查版本信息
        run: |
          echo "当前版本: ${{ needs.get_current_info.outputs.pkg_version }}"
          echo "最新版本: ${{ needs.get_latest_info.outputs.version }}"
          
          # 清理版本字符串（去除可能的空格和引号）
          CURRENT_VERSION=$(echo "${{ needs.get_current_info.outputs.pkg_version }}" | tr -d ' "')
          NEW_VERSION=$(echo "${{ needs.get_latest_info.outputs.version }}" | tr -d ' "')
          
          echo "清理后的当前版本: $CURRENT_VERSION"
          echo "清理后的最新版本: $NEW_VERSION"
          
          # 检查是否确实需要更新
          if [ "$CURRENT_VERSION" = "$NEW_VERSION" ]; then
            echo "版本相同，无需更新。但为了调试会继续执行。"
          else
            echo "版本不同，需要更新。"
          fi
          
      - id: checkout
        name: checkout
        uses: actions/checkout@v4
        with:
          repository: Misaka009982/OpenWrt-nikki
          ref: main
          path: OpenWrt-nikki
          fetch-depth: 0
          token: ${{ github.token }}
          
      - id: git_config
        name: 配置 Git
        run: |
          cd OpenWrt-nikki
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch --all
          git branch -a
          
      - id: verify_hash
        name: 验证哈希值
        run: |
          # 检查是否有哈希值
          if [ -z "${{ needs.get_latest_info.outputs.hash }}" ]; then
            echo "警告：未获取到哈希值，将中止更新"
            exit 1
          else
            echo "获取到哈希值: ${{ needs.get_latest_info.outputs.hash }}"
            echo "HASH=${{ needs.get_latest_info.outputs.hash }}" >> $GITHUB_ENV
            echo "VERSION=${{ needs.get_latest_info.outputs.version }}" >> $GITHUB_ENV
            echo "RELEASE_DATE=${{ needs.get_latest_info.outputs.release_date }}" >> $GITHUB_ENV
          fi
          
      - id: update
        name: update
        run: |
          # 显示当前 Makefile 内容
          echo "当前 Makefile 内容:"
          cat OpenWrt-nikki/nikki/Makefile
          
          # 检查 Makefile 文件是否存在并且包含必要的字段
          if ! grep -q "PKG_VERSION:=" OpenWrt-nikki/nikki/Makefile; then
            echo "错误: Makefile 中未找到 PKG_VERSION 字段，请检查文件路径和内容"
            cat OpenWrt-nikki/nikki/Makefile
            exit 1
          fi
          
          # 更新 Makefile 中的版本号和哈希值（使用更安全的替换方式）
          sed -i '/PKG_VERSION:=/c\PKG_VERSION:=${{ env.VERSION }}' OpenWrt-nikki/nikki/Makefile
          sed -i '/PKG_RELEASE:=/c\PKG_RELEASE:=1' OpenWrt-nikki/nikki/Makefile
          
          # 根据 Makefile 格式动态处理 PKG_HASH 字段
          if grep -q "PKG_HASH:=" OpenWrt-nikki/nikki/Makefile; then
            sed -i '/PKG_HASH:=/c\PKG_HASH:=${{ env.HASH }}' OpenWrt-nikki/nikki/Makefile
          else
            # 如果使用的是 PKG_SOURCE_HASH 或其他变体
            field_name=$(grep -E "PKG_.*HASH:=" OpenWrt-nikki/nikki/Makefile | head -1 | cut -d':' -f1)
            if [ -n "$field_name" ]; then
              echo "找到替代哈希字段: $field_name"
              sed -i "/${field_name}:=/c\\${field_name}:=${{ env.HASH }}" OpenWrt-nikki/nikki/Makefile
            else
              echo "警告: 未找到哈希字段，将添加 PKG_HASH 字段"
              # 在 PKG_VERSION 行之后添加 PKG_HASH
              sed -i "/PKG_VERSION:=/a PKG_HASH:=${{ env.HASH }}" OpenWrt-nikki/nikki/Makefile
            fi
          fi
          
          # 显示修改后的 Makefile 内容
          echo "修改后的 Makefile 内容:"
          cat OpenWrt-nikki/nikki/Makefile
          
          # 检查是否有变更
          if git -C OpenWrt-nikki diff --quiet nikki/Makefile; then
            echo "警告: Makefile 没有任何变更，强制修改版本以确保有提交内容"
            # 添加注释以确保文件有变更
            echo "# Updated by GitHub Actions on $(date)" >> OpenWrt-nikki/nikki/Makefile
          fi
          
      - id: create_pr
        name: 创建 PR
        run: |
          cd OpenWrt-nikki
          # 检查 Git 状态
          git status
          
          # 创建新分支
          git checkout -b dependabot
          
          # 添加修改过的文件
          git add nikki/Makefile
          
          # 显示将要提交的变更
          git diff --cached
          
          # 提交变更（允许空提交以便工作流继续）
          git commit -m "build: update mihomo to v${{ env.VERSION }}" || echo "没有变更可提交，但继续执行"
          
          # 推送分支
          git push --force origin dependabot
          
          # 检查是否已有相同主题的 PR
          if gh pr list --state open --base main | grep -q "update mihomo to v${{ env.VERSION }}"; then
            echo "已存在更新到 v${{ env.VERSION }} 的 PR，跳过创建新 PR"
          else
            # 使用 GitHub CLI 创建 PR
            gh pr create --title "build: update mihomo to v${{ env.VERSION }}" \
                         --body "将 mihomo 更新到最新版本: v${{ env.VERSION }}
            
            发布日期: ${{ env.RELEASE_DATE }}
            源代码包哈希值: ${{ env.HASH }}
            
            [发布详情](https://github.com/metacubex/mihomo/releases/tag/v${{ env.VERSION }})" \
                         --base main || echo "创建 PR 失败，可能已存在"
          fi
        env:
          GITHUB_TOKEN: ${{ github.token }}
